### ISSUE TITLE
-bash: ./tf_serving_exporter.py: Permission denied

### ISSUE THREAD

**Issue by cchung100m** [ynqa/tf_serving_exporter#2]
Hi @ynqa,

I am successfully build and run tf_serving_exporter but encounter some starting issue(Permission denied), can you please help to lookup the root cause, thanks.

```
root@59dbb35082c6:/downloads# cd tf_serving_exporter/
root@59dbb35082c6:/downloads/tf_serving_exporter# bazel build //:tf_serving_exporter
WARNING: ignoring http_proxy in environment.
..............
WARNING: /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/external/protobuf_archive/WORKSPACE:1: Workspace name in /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
INFO: Analysed target //:tf_serving_exporter (27 packages loaded).
INFO: Found 1 target...
INFO: From ProtoCompile external/tf_serving/tensorflow_serving/apis/model_pb2.py:
external/protobuf_archive/python: warning: directory does not exist.
INFO: From ProtoCompile external/protobuf_archive/python/google/protobuf/any_pb2.py:
external/protobuf_archive/python: warning: directory does not exist.
INFO: From ProtoCompile external/tf_serving/tensorflow_serving/util/status_pb2.py:
external/protobuf_archive/python: warning: directory does not exist.
bazel-out/k8-fastbuild/genfiles/external/org_tensorflow: warning: directory does not exist.
external/protobuf_archive/python: warning: directory does not exist.
INFO: From ProtoCompile external/tf_serving/tensorflow_serving/apis/get_model_status_pb2.py:
external/protobuf_archive/python: warning: directory does not exist.
external/protobuf_archive/python: warning: directory does not exist.
external/protobuf_archive/python: warning: directory does not exist.
bazel-out/k8-fastbuild/genfiles/external/org_tensorflow: warning: directory does not exist.
external/protobuf_archive/python: warning: directory does not exist.
INFO: From ProtoCompile external/org_tensorflow/tensorflow/core/example/example_pb2.py:
external/protobuf_archive/python: warning: directory does not exist.
Target //:tf_serving_exporter up-to-date:
  bazel-bin/tf_serving_exporter
INFO: Elapsed time: 160.978s, Critical Path: 11.97s
INFO: Build completed successfully, 196 total actions

```

root@59dbb35082c6:/downloads/tf_serving_exporter# ls -ltrh

```
total 56K
-rw-r-xr-x 1 root root 3.9K Jun 20 10:18 tf_serving_exporter.py
-rw-r--r-- 1 root root   25 Jun 20 10:18 requirements.txt
drwxr-xr-x 2 root root 4.0K Jun 20 10:18 example
-rw-r--r-- 1 root root 2.4K Jun 20 10:18 WORKSPACE
-rw-r--r-- 1 root root 1.7K Jun 20 10:18 README.md
-rw-r--r-- 1 root root  12K Jun 20 10:18 LICENSE
-rw-r--r-- 1 root root 1.1K Jun 20 10:18 BUILD
lrwxrwxrwx 1 root root   92 Jun 20 11:03 bazel-tf_serving_exporter -> /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/execroot/tf_serving_exporter
lrwxrwxrwx 1 root root  124 Jun 20 11:03 bazel-testlogs -> /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/execroot/tf_serving_exporter/bazel-out/k8-fastbuild/testlogs
lrwxrwxrwx 1 root root  102 Jun 20 11:03 bazel-out -> /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/execroot/tf_serving_exporter/bazel-out
lrwxrwxrwx 1 root root  124 Jun 20 11:03 bazel-genfiles -> /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/execroot/tf_serving_exporter/bazel-out/k8-fastbuild/genfiles
lrwxrwxrwx 1 root root  119 Jun 20 11:03 bazel-bin -> /root/.cache/bazel/_bazel_root/a7587c65f4a411406b639fb055a050b8/execroot/tf_serving_exporter/bazel-out/k8-fastbuild/bin
```

**root@59dbb35082c6:/downloads/tf_serving_exporter# tf_serving_exporter.py**
`-bash: ./tf_serving_exporter.py: Permission denied`

system information:

> OS version: Ubuntu 16.04.3 LTS
> bazel version: 0.11.0
> java version: openjdk version "1.8.0_171"
> 
> pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
> 
> pip list | grep -i "tensorflow"
> tensorflow (1.8.0)
> tensorflow-gpu (1.4.0)
> tensorflow-serving-api-python3 (1.7.0)
> tensorflow-tensorboard (0.4.0)
> 
> apt list | grep -i "tensorflow"
> tensorflow-model-server/unknown,now 1.8.0 all [installed]
> tensorflow-model-server-universal/unknown 1.8.0 all

**Comment by ynqa** [comment]
Thanks for reporting! How is when running with `./bazel-bin/tf_serving_exporter`?

**Comment by ynqa** [comment]
@cchung100m Thanks for reporting! How is when running with ./bazel-bin/tf_serving_exporter?
To begin with, causing permission denied for this .py file is the strange state, hmmm...

**Comment by cchung100m** [comment]
Hi @ynqa ,

I solved the permission denied error once I specific to use python3 on the code, however, I am facing the api error now, do you know how to solve it?

```
root@59dbb35082c6:/notebooks/downloads/tf_serving_exporter# python3 tf_serving_exporter.py
Traceback (most recent call last):
  File "tf_serving_exporter.py", line 11, in <module>
    from tensorflow_serving.apis import get_model_status_pb2, model_service_pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_serving/apis/get_model_status_pb2.py", line 41, in <module>
    dependencies=[tensorflow__serving_dot_apis_dot_get__model__status__pb2.DESCRIPTOR,])
AttributeError: module 'tensorflow_serving.apis.get_model_status_pb2' has no attribute 'DESCRIPTOR
```

System Information:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

root@59dbb35082c6:/notebooks/downloads/examples# pip list | grep -i "tensorflow"
tensorflow             1.7.0
tensorflow-gpu         1.4.0
tensorflow-serving-api 1.7.0
tensorflow-tensorboard 0.4.0


root@59dbb35082c6:/downloads# apt list | grep -i "tensorflow"
tensorflow-model-server/unknown,now 1.8.0 all [installed]
tensorflow-model-server-universal/unknown 1.8.0 all


root@59dbb35082c6:/downloads# apt show tensorflow-model-server
Package: tensorflow-model-server
Version: 1.8.0
Built-Using: Bazel
Priority: optional
Section: contrib/devel
Maintainer: TensorFlow Serving team
Installed-Size: unknown
Homepage: https://github.com/tensorflow/serving
Download-Size: 98.0 MB
APT-Manual-Installed: yes
APT-Sources: http://storage.googleapis.com/tensorflow-serving-apt stable/tensorflow-model-server amd64 Packages
Description: TensorFlow Serving ModelServer
```

**Comment by ynqa** [comment]
@cchung100m please build/run with python2. 3 is not supported by tf serving, probably.

**Comment by ynqa** [comment]
@cchung100m `bazel build` also generates codes (include also `get_model_status_pb2`) from .proto files, and executable binary (resolve ImportError also) in bazel-bin. So you must run with `./bazel-bin/tf_serving_exporter`.

**Comment by cchung100m** [comment]
@ynqa ,
sorry for the late reply.

Yes, bazel build from the source source code can generate the get_model_status_pb2 file but I do not have the monitoring requirement for tensorflow-serving currently, maybe I will come back to try it later.
I will close this issue since the 'Permission denied' was solved.

Thanks again for your kindly help, :-D

**Comment by ynqa** [comment]
@cchung100m I'm glad to help you, and thank you also for submitting an issue! FYI, It's tackling the issue like this: kubeflow/kubeflow#1036.
